name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 0 点，即北京时间早上 8 点
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: chokcoco/iCSS
          upstream_sync_branch: main
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 上游 Workflow 有变更，GitHub 自动暂停自动更新，请手动 Sync 一次。"
          exit 1
