name: Sync css-animation

on:
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间 08:00 自动同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Sync from upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub token 进行身份验证
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          # 克隆上游项目并通过 GITHUB_TOKEN 认证
          git clone https://github.com/chokcoco/iCSS upstream
          cd upstream

          # 更新远程仓库的 URL（使用 GitHub token 进行 push）
          git remote set-url origin https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          git push --force origin HEAD:master
