name: Sync css-animation

on:
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间 8:00 同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Sync from upstream
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          # 克隆上游项目（使用 GitHub token 方式）
          git clone --depth=1 https://github.com/chokcoco/iCSS upstream
          cd upstream

          # 推送覆盖当前 repo（你的是 master 分支）
          git remote set-url origin https://${TOKEN}@github.com/${{ github.repository }}.git
          git push --force origin HEAD:master

